name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
      fail-fast: false
    env:
      Z3_VERSION: "4.11.2"
    steps:
      - uses: actions/checkout@v3
      - name: Install Z3
        run: |
          wget https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/z3-${Z3_VERSION}-x64-glibc-2.31.zip
          unzip z3-${Z3_VERSION}-x64-glibc-2.31.zip
          echo `pwd`/z3-${Z3_VERSION}-x64-glibc-2.31/bin >> $GITHUB_PATH
      - name: Install toolchain ${{ matrix.toolchain }}
        run: |
          rustup set auto-self-update disable
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo fmt --check
